FROM mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview8-alpine AS publish
# Setup NodeJs
RUN apk update
RUN apk add --update npm=10.14.2-r0

# install trx2junit
ENV PATH="${PATH}:/root/.dotnet/tools"
RUN dotnet tool install -g trx2junit

# Cache NuGet packages
WORKDIR /src
COPY ["LibraryWebsite.sln", "."]
COPY ["LibraryWebsite/*.csproj", "LibraryWebsite/"]
COPY ["LibraryWebsite.Test/*.csproj", "LibraryWebsite.Test/"]
COPY ["LibraryWebsite.TestEndToEnd/*.csproj", "LibraryWebsite.TestEndToEnd/"]
COPY ["LibraryWebsite.TestDatabase/*.csproj", "LibraryWebsite.TestDatabase/"]
RUN dotnet restore

# Cache node_modules
WORKDIR /src
COPY ["LibraryWebsite/ClientApp/package.json","LibraryWebsite/ClientApp/package-lock.json", "LibraryWebsite/ClientApp/"]
RUN cd /src/LibraryWebsite/ClientApp; npm install

# copy remaining application files
COPY . .

# build solution
RUN dotnet build "LibraryWebsite.sln" -c Release --no-restore

# enable execution permission for shell files
RUN ["chmod", "+x", "./run_tests_in_docker.sh"]
RUN ["chmod", "+x", "./IntegrationTest/wait_for_it.sh"]

ENTRYPOINT ["sh", "./run_tests_in_docker.sh"]