version: "3.2"
services:
    website:
        # Image used in CI
        image: "radekfalhar/librarywebsite"

        # Build when running locally
#        build: 
#            context: ..
#            dockerfile: LibraryWebsite/Dockerfile
        hostname: website
#        Not really needed, just keeping it her for posterity
#        ports:
#           - "80:80"
        depends_on:
            - db
        environment:
            "ConnectionStrings:Database": "Server=db;Database=Library;User=sa;Password=Your_password123;"
            "Logging:LogLevel:Default": "Debug"
            "MigrateOnStartup": "true"

    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"

    end_to_end_test:
        build: 
            context: .
            dockerfile: LibraryWebsite.TestEndToEnd/Dockerfile
        depends_on:
            - website
        environment:
            "WEB_ADDRESS": "website:80"
        volumes:
            - "./TestResults:/src/TestResults"