version: "3.4"
services:
    website:
        # Build when running locally
        build: 
            context: .
            dockerfile: Dockerfile
            target: final
        hostname: website
        ports:
           - "54321:80"
        depends_on:
            - db
        environment:
            "ASPNETCORE_ENVIRONMENT": "Staging"
            "ConnectionStrings:Database": "Server=db;Database=Library;User=sa;Password=Your_password123;"

    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"        

    selenium_hub:
        image: selenium/hub:3.14.0-gallium
        depends_on: 
            - website
        ports:
            - "4444:4444"

    selenium_chrome:
        image: selenium/node-chrome:3.14.0-gallium
        volumes:
          - /dev/shm:/dev/shm
        depends_on:
          - selenium_hub
        environment:
            HUB_HOST: selenium_hub