version: "3.2"
services:

    volumes-provisioner:
        image: hasnat/volumes-provisioner
        environment:
            PROVISION_DIRECTORIES: "1000:1000:0755:/tmp/certs"
        volumes:
            - "./certs:/tmp/certs"
        network_mode: none
    cert-gen:
        image: eventstore/es-gencert-cli:1.0.2
        entrypoint: bash
        command: >
            -c 'es-gencert-cli create-ca -out /tmp/certs/ca &&
                es-gencert-cli create-node -ca-certificate /tmp/certs/ca/ca.crt -ca-key /tmp/certs/ca/ca.key -out \
                /tmp/certs/node1 -ip-addresses 127.0.0.1,172.30.240.11'
        user: "1000:1000"
        volumes:
            - "./certs:/tmp/certs"
        depends_on:
            - volumes-provisioner