version: "3.2"
services:
    website:
        image: "radekfalhar/librarywebsite"
        hostname: website
#        Not really needed, just keeping it her for posterity
#        ports:
#           - "80:80"
#           - "443:443:
        depends_on:
            - eventstore
        environment:
            "ASPNETCORE_ENVIRONMENT": "Staging"
            "ConnectionStrings:EventStore": "esdb://admin:changeit@eventstore:2113/?TlsVerifyCert=false"

    eventstore:
        image: eventstore/eventstore:20.6.1-bionic
        environment:
            - EVENTSTORE_CERTIFICATE_FILE=/etc/eventstore/certs/node1/node.crt
            - EVENTSTORE_CERTIFICATE_PRIVATE_KEY_FILE=/etc/eventstore/certs/node1/node.key
            - EVENTSTORE_TRUSTED_ROOT_CERTIFICATES_PATH=/etc/eventstore/certs/ca
        ports:
            - 1111:1113
            - 2111:2113
        volumes:
            - ./certs:/etc/eventstore/certs
        restart: unless-stopped

    end_to_end_test:
        build: 
            context: .
            dockerfile: Dockerfile-test
        depends_on:
            - website
            - selenium_hub
        command: endToEnd
        environment:
            "WEB_ADDRESS": "website:443"
            "SELENIUM_HUB": "http://selenium_hub:4444/wd/hub/"
        volumes:
            - "./TestResults:/src/TestResults"

    selenium_hub:
        image: selenium/hub:3.14.0-gallium
        depends_on: 
            - website
        ports:
            - "4444:4444"

    selenium_chrome:
        image: selenium/node-chrome:3.14.0-gallium
        volumes:
          - /dev/shm:/dev/shm
        depends_on:
          - selenium_hub
        environment:
            HUB_HOST: selenium_hub