FROM mcr.microsoft.com/dotnet/core/sdk:3.1.302-alpine3.12 AS publish

# enable globalization support
RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

# install trx2junit
ENV PATH="${PATH}:/root/.dotnet/tools"
RUN dotnet tool install -g trx2junit

# Cache NuGet packages
WORKDIR /src
COPY ["LibraryWebsite.sln", "."]
COPY ["LibraryWebsite/LibraryWebsite.csproj", "LibraryWebsite/"]
COPY ["LibraryWebsite.Client/LibraryWebsite.Client.csproj", "LibraryWebsite.Client/"]
COPY ["LibraryWebsite.Shared/LibraryWebsite.Shared.csproj", "LibraryWebsite.Shared/"]
COPY ["LibraryWebsite.Test/LibraryWebsite.Test.csproj", "LibraryWebsite.Test/"]
COPY ["LibraryWebsite.TestEndToEnd/LibraryWebsite.TestEndToEnd.csproj", "LibraryWebsite.TestEndToEnd/"]
COPY ["LibraryWebsite.TestDatabase/LibraryWebsite.TestDatabase.csproj", "LibraryWebsite.TestDatabase/"]
RUN dotnet restore

# copy remaining application files
COPY . .

# build solution
RUN dotnet build "LibraryWebsite.sln" -c Release --no-restore

# enable execution permission for shell files
RUN ["chmod", "+x", "./run_tests_in_docker.sh"]
RUN ["chmod", "+x", "./IntegrationTest/wait_for_it.sh"]

ENTRYPOINT ["sh", "./run_tests_in_docker.sh"]