version: 2
jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0-buster

    steps:
      - checkout
      - run:
          name: Run Tests
          command: dotnet test -c Release --logger "trx"
      - run:
          name: Convert test results from trx to junit
          when: always
          command: |
              export PATH="$PATH:/root/.dotnet/tools"
              dotnet tool install -g trx2junit
              trx2junit **/TestResults/*.trx --output TestResults/dotnet
      - store_test_results:
          path: TestResults
      - store_artifacts:
          path: TestResults
          destination: TestResults

  publish:
    docker:
      - image: circleci/python:3.7.3

    steps:
      - checkout

      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker build . -f LibraryWebsite/Dockerfile -t euphoric/librarywebsite:${CIRCLE_BRANCH}-${CIRCLE_TAG}
#            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
#            docker push ariv3ra/$IMAGE_NAME:$TAG

workflows:
  version: 2
  build_and_publish:
    jobs:
      - test
      - publish:
          requires:
            - test
